// NDPS Act sample drug database & factor lists.
// Threshold values are illustrative for prototype purposes only.

const SUBSTANCES = [
  {
    name: "Cannabis (Ganja)",
    section: "20(b)(ii)",
    smallQty: 1000,  // grams
    commercialQty: 20000,
    unit: "Gram",
    chemical: "—",
    common: "Cannabis (Ganja)",
    otherName: "—",
    notif: "S.O. 1055(E)",
    notifDate: "19-10-2001",
    iupacName: "—",
    iupacWeb: "—",
    notifLink: "egazette.gov.in",
  },
  {
    name: "Charas / Hashish",
    section: "20(b)(ii)",
    smallQty: 100,
    commercialQty: 1000,
    unit: "Gram",
    chemical: "Cannabis resin",
    common: "Charas / Hashish",
    otherName: "—",
    notif: "S.O. 1055(E)",
    notifDate: "19-10-2001",
    iupacName: "—",
    iupacWeb: "—",
    notifLink: "egazette.gov.in",
  },
  {
    name: "Heroin (Diacetylmorphine)",
    section: "21(c)",
    smallQty: 5,
    commercialQty: 250,
    unit: "Gram",
    chemical: "(5α,6α)-7,8-Didehydro-4,5-epoxy-17-methylmorphinan-3,6-diol diacetate",
    common: "Heroin",
    otherName: "Diamorphine",
    notif: "S.O. 1055(E)",
    notifDate: "19-10-2001",
    iupacName: "Morphine diacetate",
    iupacWeb: "pubchem.ncbi.nlm.nih.gov/compound/5462328",
    notifLink: "egazette.gov.in",
  },
  {
    name: "Cocaine",
    section: "21(c)",
    smallQty: 2,
    commercialQty: 100,
    unit: "Gram",
    chemical: "Methyl (1R,2R,3S,5S)-3-(benzoyloxy)-8-methyl-8-azabicyclo[3.2.1]octane-2-carboxylate",
    common: "Cocaine",
    otherName: "Coke",
    notif: "S.O. 1055(E)",
    notifDate: "19-10-2001",
    iupacName: "Methyl benzoylecgonine",
    iupacWeb: "pubchem.ncbi.nlm.nih.gov/compound/446220",
    notifLink: "egazette.gov.in",
  },
  {
    name: "Opium",
    section: "17(c)",
    smallQty: 25,
    commercialQty: 2500,
    unit: "Gram",
    chemical: "Mixture of alkaloids from Papaver somniferum",
    common: "Opium",
    otherName: "Raw opium",
    notif: "S.O. 1055(E)",
    notifDate: "19-10-2001",
    iupacName: "—",
    iupacWeb: "—",
    notifLink: "egazette.gov.in",
  },
  {
    name: "MDMA (Ecstasy)",
    section: "22(c)",
    smallQty: 0.5,
    commercialQty: 10,
    unit: "Gram",
    chemical: "3,4-Methylenedioxy-N-methylamphetamine",
    common: "MDMA",
    otherName: "Ecstasy / Molly",
    notif: "S.O. 1055(E)",
    notifDate: "19-10-2001",
    iupacName: "1-(2H-1,3-benzodioxol-5-yl)-N-methylpropan-2-amine",
    iupacWeb: "pubchem.ncbi.nlm.nih.gov/compound/1615",
    notifLink: "egazette.gov.in",
  },
  {
    name: "Methamphetamine",
    section: "22(c)",
    smallQty: 2,
    commercialQty: 50,
    unit: "Gram",
    chemical: "N-methyl-1-phenylpropan-2-amine",
    common: "Methamphetamine",
    otherName: "Meth / Ice",
    notif: "S.O. 1055(E)",
    notifDate: "19-10-2001",
    iupacName: "(S)-N-methyl-1-phenylpropan-2-amine",
    iupacWeb: "pubchem.ncbi.nlm.nih.gov/compound/10836",
    notifLink: "egazette.gov.in",
  },
];

const UNITS = { Gram: 1, Kilogram: 1000, Milligram: 0.001 };

// Aggravating factors (illustrative survey-suggested averages)
const AGGRAVATING = [
  { id: "a1",  label: "Use of minors or vulnerable persons.", sentence: 0, fine: 0, avg: 18 },
  { id: "a2",  label: "Sales in or around Educational and Social Welfare Institutes.", sentence: 0, fine: 0, avg: 15 },
  { id: "a3",  label: "Part of a Drug Mafia or Syndicate.", sentence: 0, fine: 0, avg: 22 },
  { id: "a4",  label: "Link to terrorism funding.", sentence: 0, fine: 0, avg: 30 },
  { id: "a5",  label: "Link to International Trafficking.", sentence: 0, fine: 0, avg: 25 },
  { id: "a6",  label: "Use of Arms, Violence, Intimidation, Gundagardi.", sentence: 0, fine: 0, avg: 20 },
  { id: "a7",  label: "Custodian of drugs indulging in its Trade.", sentence: 0, fine: 0, avg: 16 },
  { id: "a8",  label: "Taking advantage of the public post, or position, to obtain drugs or facilitate the drug trade.", sentence: 0, fine: 0, avg: 24 },
  { id: "a9",  label: "Role: Kingpin, Ringleader, Principal Offender, Financer.", sentence: 0, fine: 0, avg: 28 },
  { id: "a10", label: "Previous conviction under the NDPS Act.", sentence: 0, fine: 0, avg: 20 },
];

// Mitigating factors
const MITIGATING = [
  { id: "m1",  label: "Confining arguments to sentence Reduction (first appeal or revision).", sentence: 0, fine: 0, avg: 10, options: ["First Appeal", "Criminal Appeal / Revision"] },
  { id: "m2",  label: "Percentage reduction for every year's delay in the Trial and Appeals.", sentence: 0, fine: 0, avg: 6 },
  { id: "m3",  label: "First Time Offender.", sentence: 0, fine: 0, avg: 12 },
  { id: "m4",  label: "Exhibition of Genuine Remorse and Profound Regret.", sentence: 0, fine: 0, avg: 8 },
  { id: "m5",  label: "Health, Social, and Economic Vulnerabilities.", sentence: 0, fine: 0, avg: 10 },
  { id: "m6",  label: "Positive Contributions.", sentence: 0, fine: 0, avg: 5 },
  { id: "m7",  label: "Drug dependence.", sentence: 0, fine: 0, avg: 9 },
  { id: "m8",  label: "Voluntarily assisting the Investigator by disclosing Sellers and Buyers.", sentence: 0, fine: 0, avg: 14 },
  { id: "m9",  label: "Minor Role, Extent of involvement.", sentence: 0, fine: 0, avg: 10 },
  { id: "m10", label: "Family obligations / dependents.", sentence: 0, fine: 0, avg: 7 },
];

Object.assign(window, { SUBSTANCES, UNITS, AGGRAVATING, MITIGATING });
